
alg:
  desc: algorithm (fl or ringsfl or sl or splitfed)
  value: !!str ringsfl
model_type:
  desc: Model structure
  value: !!str resnet18 # mlp or vgg16 or resnet18 or cnn or mobilenet or mobilenet_simple
dataset_name:
  desc: Dataset for training
  value: !!str cifar10 # mnist or cifar10
dataset_type:
  desc: IID or Non-IID
  value: !!str iid
dataset_blocknum:
  desc: How many blocks to divide the dataset into
  value: !!int 781
local_epoch:
  desc: Local iteration num of each node
  value: !!int 2
global_round:
  desc: Global round num of system
  value: !!int 6
learning_rate:
  desc: Learning rate
  value: !!float 0.1
batch_size:
  desc: Batch size
  value: !!int 64
cut_point:
  value: !!int 2